# Configure notification
notifications:
  email:
    on_success: never
    on_failure: never

os:
  - linux
  - osx

env:
  - R_VERSION=r-base

matrix:
  exclude:
    - os: osx
      env: R_VERSION=r-base

language: bash

install:
  # Install miniconda
  - source deploy/travis_install.sh
  # Update conda and install packages
  - conda update --yes conda
  - conda install --yes conda-build jinja2 anaconda-client

script:
  - mkdir out
  - conda build deploy/conda-recipe --output-folder out

after_success:
  - test $TRAVIS_BRANCH = "master" &&
    anaconda -t $CONDA_UPLOAD_TOKEN upload --force out/$TRAVIS_OS_NAME-64/*.tar.bz2

# We only want to build with Travis when pushing to master or PR:
# https://stackoverflow.com/a/31882307/2169986
branches:
  only:
    - master

