#{% set version = '0.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-woofr
  version: {{ GIT_DESCRIBE_TAG }}
  #version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/pdiakumis/woofr
  git_tag: master

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, testthat,
requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-purrr
    - r-readr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-yaml

  run:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-purrr
    - r-readr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-yaml

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('woofr')"           # [not win]
    - "\"%R%\" -e \"library('woofr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/pdiakumis/woofr
  license: MIT + file LICENSE
  summary: Helper R Functions for [woof](https://github.com/umccr/woofr).
  license_family: MIT

